PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT DISTINCT ?item WHERE {
{ ?item wdt:P17 wd:Q265 . }
      UNION { ?item wdt:P159/wdt:P17 wd:Q265 . }
      ?item wdt:P31/wdt:P279* wd:Q43229 .
} ORDER BY ?item LIMIT 50
